kind: Service
apiVersion: v1
metadata:
  name: abl-ambulance-webapi
spec:
  selector:
    pod: abl-ambulance-webapi-label
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: webapi-port
